sudo: false
language: python
python:
    #- "2.6"
    #- "2.7"
    #- "3.3"
    #- "3.4"
    #- "3.5"
  - "3.6"
    #- "3.7-dev"
    #- "pypy"
    #- "pypy3"

cache:
  pip: true
  directories:
    - .venv

env:
  global:
    - RANDOM_SEED=0
    - PIPENV_NOSPIN=true

install: "make"

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
  - make ci

jobs:
  include:
    - stage: test
      script:
        - |
          if [[ "$TRAVIS_PYTHON_VERSION" != "2.6" ]] ; then make test-readme; fi
        - make ci
    - stage: coverage
      python: 3.6
      script: codecov
